name: Greetings

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the WGEasy project! Thank you for opening your first issue. Our team will look into it as soon as possible.'
        pr-message: 'Thank you for submitting your first pull request! We really appreciate your contribution.'
